# Docker Mastery Multi-Language Learning Path - Minimal Pre-commit Configuration
# =============================================================================
# Essential quality checks that work reliably across all environments

repos:
  # =============================================================================
  # General Code Quality & Formatting
  # =============================================================================
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      # File Quality
      - id: check-yaml                  # Valid YAML syntax
      - id: check-json                  # Valid JSON syntax
      - id: check-merge-conflict        # No merge conflict markers
      - id: check-case-conflict         # No case conflicts
      - id: check-executables-have-shebangs  # Scripts have shebangs

      # Whitespace & Formatting
      - id: trailing-whitespace         # Remove trailing whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer          # Ensure files end with newline
      - id: mixed-line-ending          # Consistent line endings

  # =============================================================================
  # Python (for Python track)
  # =============================================================================
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3
        files: \.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--profile, black]
        files: \.py$

  # =============================================================================
  # Educational Content Checks
  # =============================================================================
  - repo: local
    hooks:
      # Ensure educational READMEs have proper structure
      - id: check-readme-structure
        name: Check README educational structure
        description: Ensure module READMEs follow our educational template
        entry: python3
        language: system
        files: docker-mastery-multitrack/.*/README\.md$
        args:
          - -c
          - |
            import sys, re
            content = open(sys.argv[1]).read()
            required = ['Learning Objectives', 'Time Investment']
            missing = [r for r in required if not re.search(r, content, re.IGNORECASE)]
            if missing:
                print(f'Educational content missing in {sys.argv[1]}: {missing}')
                print('Required sections: Learning Objectives, Time Investment')
                sys.exit(1)

default_install_hook_types: [pre-commit]
