services:
  task-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Hot reload source code
      - ./src:/app/src:cached
      - ./Cargo.toml:/app/Cargo.toml:ro
      # Cargo cache for faster builds
      - cargo-cache:/usr/local/cargo/registry
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug
      - ENV=development
    networks:
      - dev-network

  # Future: Add PostgreSQL for Module 04
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: tasks
  #     POSTGRES_USER: taskuser
  #     POSTGRES_PASSWORD: taskpass
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - dev-network

volumes:
  cargo-cache:

networks:
  dev-network:
