services:
  task-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        # Pass host UID/GID to avoid permission issues
        # Use: UID=$(id -u) GID=$(id -g) docker-compose up
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    volumes:
      # Hot reload source code (WARNING: bind mount permission issues possible!)
      - ./src:/app/src:cached
      # Named volume for cache (no permission issues)
      - python-cache:/app/.cache
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - LOG_LEVEL=DEBUG
    networks:
      - dev-network

  # Future: Add PostgreSQL for Module 04
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: tasks
  #     POSTGRES_USER: taskuser
  #     POSTGRES_PASSWORD: taskpass
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - dev-network

volumes:
  python-cache: # Docker-managed volume, no permission issues

networks:
  dev-network:
