services:
  task-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Hot reload source code
      - ./src:/app/src:cached
    ports:
      - "8080:8080"
    environment:
      - ENV=development
      - LOG_LEVEL=DEBUG
    networks:
      - dev-network

  # Future: Add PostgreSQL for Module 04
  # postgres:
  #   image: postgres:16-alpine
  #   environment:
  #     POSTGRES_DB: tasks
  #     POSTGRES_USER: taskuser
  #     POSTGRES_PASSWORD: taskpass
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - dev-network

networks:
  dev-network:
